# Generated by Django 5.0.1 on 2026-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Pharmacist', 'Pharmacist'), ('Patient', 'Patient'), ('Distributor', 'Distributor')], default='Patient', max_length=20),
        ),
    ]
