# Generated by Django 5.0.1 on 2026-01-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company/distributor name (for distributors)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, help_text='Professional license number (for pharmacists and distributors)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_name',
            field=models.CharField(blank=True, help_text='Legal pharmacy name (for pharmacists)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_phone',
            field=models.CharField(blank=True, help_text='Pharmacy contact phone (for pharmacists)', max_length=20, null=True),
        ),
    ]
