# Generated by Django 5.0.1 on 2026-01-15 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manifests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_type', models.CharField(help_text='Type of reporter (e.g., Pharmacist, Patient, Healthcare Worker)', max_length=50)),
                ('issue_type', models.CharField(help_text='Type of issue reported (e.g., Counterfeit Suspected, Quality Issue, Packaging Damage)', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('lot', models.ForeignKey(help_text='Lot manifest being flagged', on_delete=django.db.models.deletion.CASCADE, related_name='crowd_flags', to='manifests.lotmanifest')),
                ('user', models.ForeignKey(help_text='User who reported the issue', on_delete=django.db.models.deletion.CASCADE, related_name='crowd_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crowd Flag',
                'verbose_name_plural': 'Crowd Flags',
                'db_table': 'crowd_flags',
                'ordering': ['-created_at'],
            },
        ),
    ]
