# Generated by Django 5.0.1 on 2026-01-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdflag',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical - Immediate safety concern'), ('HIGH', 'High - Significant quality issue'), ('MEDIUM', 'Medium - Notable concern'), ('LOW', 'Low - Minor issue')], db_index=True, default='MEDIUM', help_text='Severity level of the reported issue (impacts trust score calculation)', max_length=10),
        ),
    ]
