# Generated by Django 5.0.1 on 2026-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_crowdflag_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdflag',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate of the report', null=True),
        ),
        migrations.AddField(
            model_name='crowdflag',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate of the report', null=True),
        ),
        migrations.AddField(
            model_name='crowdflag',
            name='region',
            field=models.CharField(blank=True, help_text='Geographical region or administrative area', max_length=100, null=True),
        ),
    ]
