# Generated by Django 5.0.1 on 2026-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_crowdflag_latitude_crowdflag_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdflag',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='crowdflag',
            name='date_of_purchase',
            field=models.DateField(blank=True, help_text='Date the product was purchased by the reporter', null=True),
        ),
        migrations.AddField(
            model_name='crowdflag',
            name='dispensing_pharmacy_name',
            field=models.CharField(blank=True, default='', help_text='Name of the pharmacy where the product was purchased', max_length=255),
        ),
        migrations.AddField(
            model_name='crowdflag',
            name='evidence_image',
            field=models.ImageField(blank=True, help_text='Photographic evidence of the reported issue', null=True, upload_to='reports/evidence/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='crowdflag',
            name='investigator_notes',
            field=models.TextField(blank=True, default='', help_text='Timestamped investigation notes appended by administrators'),
        ),
        migrations.AddField(
            model_name='crowdflag',
            name='status',
            field=models.CharField(choices=[('NEW', 'New — Awaiting Review'), ('INVESTIGATING', 'Under Investigation'), ('ESCALATED_DISTRIBUTOR', 'Escalated to Distributor'), ('ESCALATED_REGULATOR', 'Escalated to Regulator'), ('RESOLVED', 'Resolved'), ('CLOSED_NO_ACTION', 'Closed — No Action Required')], db_index=True, default='NEW', help_text='Current investigation lifecycle status', max_length=25),
        ),
        migrations.AlterField(
            model_name='crowdflag',
            name='issue_type',
            field=models.CharField(choices=[('COUNTERFEIT', 'Counterfeit Suspected'), ('QUALITY', 'Quality Issue'), ('PACKAGING', 'Packaging Damage'), ('ADVERSE_EVENT', 'Adverse Patient Reaction'), ('MISSING_MANIFEST', 'Missing Manifest')], help_text='Type of issue reported', max_length=100),
        ),
    ]
