# Generated by Django 5.0.1 on 2026-02-10 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0003_alter_distributor_is_verified_regulator'),
        ('manifests', '0003_alter_lotmanifest_digital_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('items', models.JSONField(help_text="List of medicines and quantities requested (e.g., [{'medicine_id': '<uuid>', 'name': 'Aspirin', 'quantity': 100}])")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the order', max_length=20)),
                ('delivery_token', models.CharField(blank=True, help_text='SHA-256 hash generated for offline verification', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(help_text='Distributor who will fulfill this order', on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to='entities.distributor')),
                ('manifest', models.OneToOneField(blank=True, help_text='Lot manifest linked to this order (creates chain of custody)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_order', to='manifests.lotmanifest')),
                ('pharmacist', models.ForeignKey(help_text='Pharmacist who placed this order', limit_choices_to={'role': 'Pharmacist'}, on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supply Order',
                'verbose_name_plural': 'Supply Orders',
                'db_table': 'supply_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
