# Generated by Django 5.0.1 on 2026-01-15 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='Medicine category (e.g., Antibiotic, Analgesic)', max_length=100)),
                ('distributor', models.ForeignKey(help_text='Distributor responsible for this medicine', on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='entities.distributor')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'medicines',
                'ordering': ['name'],
            },
        ),
    ]
