# Generated by Django 5.0.1 on 2026-01-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaceuticals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='active_ingredient',
            field=models.CharField(blank=True, default='Unknown', help_text='Active pharmaceutical ingredient (API) or generic name', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, default='Not specified', help_text='Form of medication (e.g., Tablet, Capsule, Syrup, Injection)', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer_name',
            field=models.CharField(blank=True, default='Unknown', help_text='Name of the manufacturing company', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, default='Not specified', help_text='Drug strength (e.g., 500mg, 250mg/5ml)', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, help_text='Medicine category (e.g., Antibiotic, Analgesic)', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(help_text='Product name', max_length=255),
        ),
    ]
