# Generated by Django 5.0.1 on 2026-01-15 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manifests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_coord', models.JSONField(help_text="Geographic coordinates in JSON format (e.g., {'lat': 40.7128, 'lng': -74.0060})")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(help_text='Lot manifest that was scanned/received', on_delete=django.db.models.deletion.CASCADE, related_name='receipt_events', to='manifests.lotmanifest')),
                ('user', models.ForeignKey(help_text='User who scanned/received the lot', on_delete=django.db.models.deletion.CASCADE, related_name='receipt_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Event',
                'verbose_name_plural': 'Receipt Events',
                'db_table': 'receipt_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
