# Generated by Django 5.0.1 on 2026-01-15 09:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('pharmaceuticals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
                ('digital_signature', models.TextField(help_text='Digital signature from the distributor')),
                ('trust_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Trust score based on verification (0.00 to 100.00)', max_digits=5)),
                ('distributor', models.ForeignKey(help_text='Distributor who provided this lot', on_delete=django.db.models.deletion.CASCADE, related_name='lot_manifests', to='entities.distributor')),
                ('medicine', models.ForeignKey(help_text='Medicine associated with this lot', on_delete=django.db.models.deletion.CASCADE, related_name='lot_manifests', to='pharmaceuticals.medicine')),
            ],
            options={
                'verbose_name': 'Lot Manifest',
                'verbose_name_plural': 'Lot Manifests',
                'db_table': 'lot_manifests',
                'ordering': ['-expiry_date'],
            },
        ),
    ]
