# Generated by Django 5.0.1 on 2026-01-16 19:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotmanifest',
            name='digital_signature',
            field=models.TextField(blank=True, help_text='Auto-generated HMAC-SHA512 digital signature (128 hex chars)'),
        ),
        migrations.AlterField(
            model_name='lotmanifest',
            name='trust_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Trust score based on verification (0.00 to 100.00)', max_digits=5),
        ),
    ]
