# Generated by Django 5.0.1 on 2026-01-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0002_alter_lotmanifest_digital_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotmanifest',
            name='digital_signature',
            field=models.TextField(blank=True, help_text='Auto-generated Ed25519 digital signature (128 hex chars)'),
        ),
    ]
