# Generated by Django 5.0.1 on 2026-01-15 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('public_key', models.TextField(help_text='Public key for verifying digital signatures')),
                ('is_verified_regulator', models.BooleanField(default=False, help_text='Whether this distributor is verified by regulatory authorities')),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
                'db_table': 'distributors',
                'ordering': ['name'],
            },
        ),
    ]
