# Generated by Django 5.0.1 on 2026-02-10 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='created_by',
            field=models.ForeignKey(
                null=True,  #  Allow null temporarily
                blank=True,
                help_text='User who created this distributor entity', 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='distributor_entities', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
