# Generated by Django 5.0.1 on 2026-02-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_distributor_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='is_verified_regulator',
            field=models.BooleanField(default=True, help_text='Whether this distributor is verified by regulatory authorities'),
        ),
    ]
